"""產生 supabase/seed.sql：官方事件目錄、官方 Profile、事件池與示範 World。

seed 的唯一來源是 worldpane_core.defaults / catalog，確保 DB 組裝出的設定
與 Simulation Core 的預設完全一致（tests/test_catalog.py 驗證等價性）。

    python scripts/gen_seed_sql.py > ../supabase/seed.sql
    python scripts/gen_seed_sql.py --check ../supabase/seed.sql
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date

from worldpane_core import defaults
from worldpane_core.catalog import (
    official_definition_id,
    official_definitions,
    official_profile_id,
    shared_settings,
    split_event_config,
)
from worldpane_core.profiles import OFFICIAL_PROFILES

DEMO_WORLD_ID = "00000000-0000-4000-a000-000000000001"
DEMO_START = date(2026, 10, 1)


def lit(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (dict, list)):
        return "$json$" + json.dumps(value, ensure_ascii=False, sort_keys=True) + "$json$::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


PROFILES = [(key, name, factory()) for key, (name, factory) in OFFICIAL_PROFILES.items()]

CHARACTERS = [
    # (id, appearance, display_name, profile key, sort_order)
    ("00000000-0000-4000-a000-000000000201", "xiaobai", "小白", "official.student.v1", 0),
    ("00000000-0000-4000-a000-000000000202", "xiaojimao", "小雞毛", "official.office_worker.v1", 1),
]


def render() -> str:
    out: list[str] = [
        "-- =============================================================================",
        "-- Worldpane seed — GENERATED by worldpane-core/scripts/gen_seed_sql.py. Do not edit by hand.",
        "--",
        "-- Official event catalog, official profiles + event pools, and one demo world",
        "-- (小白 + 小雞毛, couple). Every probability / weight / duration / cooldown is a",
        "-- PLACEHOLDER (spec §34 TBD); tune them in the DB, not in code:",
        "--   event_definitions.params, profile_event_pools.overrides,",
        "--   character_profiles.*_config, worlds.shared_event_config.",
        "-- Idempotent: fixed ids + ON CONFLICT DO UPDATE.",
        "-- =============================================================================",
        "",
        "-- Official event catalog",
    ]
    defs = official_definitions()
    for d in defs:
        out.append(
            "insert into worldpane.event_definitions "
            "(id, world_id, key, category, label, scene, location, activity, params, enabled, sort_order) values ("
            + ", ".join(
                lit(v)
                for v in (
                    official_definition_id(d.category, d.key), None, d.key, d.category, d.label,
                    d.scene, d.location, d.activity, dict(d.params), d.enabled, d.sort_order,
                )
            )
            + ") on conflict (id) do update set label = excluded.label, scene = excluded.scene, "
            "location = excluded.location, activity = excluded.activity, params = excluded.params, "
            "enabled = excluded.enabled, sort_order = excluded.sort_order;"
        )

    out += ["", "-- Official profiles (event lists live in profile_event_pools)"]
    for key, name, profile in PROFILES:
        settings, pool = split_event_config(profile.event_config)
        pid = official_profile_id(key)
        out.append(
            "insert into worldpane.character_profiles "
            "(id, world_id, key, name, schedule_config, meal_config, leave_config, event_config) values ("
            + ", ".join(
                lit(v)
                for v in (
                    pid, None, key, name, profile.schedule_config, profile.meal_config,
                    profile.leave_config, settings,
                )
            )
            + ") on conflict (id) do update set name = excluded.name, schedule_config = excluded.schedule_config, "
            "meal_config = excluded.meal_config, leave_config = excluded.leave_config, event_config = excluded.event_config;"
        )
        for category, ev_key, overrides in pool:
            out.append(
                "insert into worldpane.profile_event_pools (profile_id, event_definition_id, overrides) values ("
                + ", ".join(lit(v) for v in (pid, official_definition_id(category, ev_key), overrides))
                + ") on conflict (profile_id, event_definition_id) do update set overrides = excluded.overrides;"
            )

    out += ["", "-- Demo world"]
    shared = shared_settings(defaults.default_shared_event_config())
    shared["overrides"] = {}
    out.append(
        "insert into worldpane.worlds (id, name, timezone, simulation_version, simulation_start_date, shared_event_config) values ("
        + ", ".join(
            lit(v)
            for v in (DEMO_WORLD_ID, "窗間 Demo", defaults.DEFAULT_TIMEZONE, 1, DEMO_START.isoformat(), shared)
        )
        + ") on conflict (id) do update set shared_event_config = excluded.shared_event_config;"
    )
    for cid, appearance, name, profile_key, order in CHARACTERS:
        out.append(
            "insert into worldpane.characters (id, world_id, appearance_key, display_name, profile_id, sort_order) values ("
            + ", ".join(lit(v) for v in (cid, DEMO_WORLD_ID, appearance, name, official_profile_id(profile_key), order))
            + ") on conflict (id) do nothing;"
        )
    out.append(
        "insert into worldpane.character_relationships (id, world_id, character_a_id, character_b_id, relationship_type) values ("
        + ", ".join(
            lit(v)
            for v in (
                "00000000-0000-4000-a000-000000000301", DEMO_WORLD_ID, CHARACTERS[0][0], CHARACTERS[1][0], "couple",
            )
        )
        + ") on conflict (id) do nothing;"
    )
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", metavar="PATH", help="exit 1 if PATH differs from the generated seed")
    args = parser.parse_args()
    sql = render()
    if args.check:
        with open(args.check, encoding="utf-8") as fh:
            if fh.read() != sql:
                print(f"{args.check} is stale; regenerate with scripts/gen_seed_sql.py", file=sys.stderr)
                return 1
        return 0
    sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
